version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update --remote
      - run:
          name: build
          command: make
      - run:
          name: test
          command: ./test
